image: node:latest

pages:
  only:
  - master

  cache:
    paths:
    - node_modules/

  before_script:
  - git config user.email 'devbot@ilusons.com'
  - git config user.name 'Dev Bot'

  - git remote set-url origin https://$GITHUB_USER:$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_PATH.git

  script:
  - npm install gatsby-cli -g
  - npm install
  - npm run deploy

  artifacts:
    paths:
    - public
